myapp:
  build: .
  ports:
    - 3000:3000
  command: supervisord -c /etc/supervisor/supervisord.conf -n
  environment:
    - PATH=$PATH:/usr/local/nvm/versions/node/v5.5.0/bin/
    - APP_PORT=3000
    - APP_ENV=development
